### ISSUE TITLE
Profiles do not work

### ISSUE THREAD

**Issue by mfabiani53** [tcarlsen/lovelace-light-with-profiles#10]
I followed all your installation docs, put the light_profiles.csv inside the /config folder, added the entry light_profiles inside the ui.lovelace.yaml with the same values of light_profiles.csv, added the card inside ui.lovelace.yaml. but this is what i get:

![Schermata 2020-10-25 alle 14 23 22](https://user-images.githubusercontent.com/37701688/97108418-b7a3bc80-16cd-11eb-83ec-bd4a05fa9f02.png)

I am able to turn on and off the lights, but clicking over a profile it do not nothing. Nothing change...

For more informations my light_profile.csv is:

```
bright,0.5119,0.4147,254
dimmed,0.5119,0.4147,77
nightlight,0.363,0.3686,1
```

And this is what i added into ui.lovelace.yaml:

```
light_profiles:
  bright: '0.5119,0.4147,254'
  dimmed: '0.5119,0.4147,77'
  nightlight: '0.363,0.3686,1'
```

My card is:

```
  - title: Profili Luci
    path: profili
    icon: mdi:lightbulb
    cards:
      - type: custom:light-with-profiles
        title: Profili Luci
        debug: true
        entities:
          - entity: light.yeelight_1
            profiles:
              - name: bright
                icon: 'mdi:brightness-5'
              - name: dimmed
                icon: 'mdi:brightness-4'
              - name: nightlight
                icon: 'mdi:brightness-3'
          - entity: light.yeelight_2
            profiles:
              - name: bright
                icon: 'mdi:brightness-5'
              - name: dimmed
                icon: 'mdi:brightness-4'
              - name: nightlight
                icon: 'mdi:brightness-3'
          - entity: light.yeelight_5
            profiles:
              - name: bright
                icon: 'mdi:brightness-5'
              - name: dimmed
                icon: 'mdi:brightness-4'
              - name: nightlight
                icon: 'mdi:brightness-3'
          - entity: light.yeelight_9
            profiles:
              - name: bright
                icon: 'mdi:brightness-5'
              - name: dimmed
                icon: 'mdi:brightness-4'
              - name: nightlight
                icon: 'mdi:brightness-3'
```

I am running HASSOS 0.116.4 inside a RPi4

**Comment by thisisastoryof** [comment]
Hi @mfabiani53,
I currently have the same issue. I'm on RPi4 and 0.116.0.
Also have double-checked my two configs + card debug mode.

Nevertheless, it seems like you're using non RGB lights (x,y: null), is that correct?
In that case both your `light_profiles.csv` and the profiles in your `ui-lovelace.yaml` must contains zeros:

**light_profiles.csv**
```
id,x,y,brightness
bright,0,0,254
```

and

**ui-lovelace.yaml**
```
light_profiles:
  bright: '0,0,254'
```

and then in debug mode you should see `x,y: null brightness: 254`

Almost a year ago I've struggled with the issue that just RGB lights were supported by the card.
It's documented in the [Home Assistant forum](https://community.home-assistant.io/t/lovelace-card-light-with-profiles/121398/24?u=mcg) (also see the following posts).

**Comment by fantnhu** [comment]
Hi! The same problem:

_with debug:
x,y:null brightness:148_

I can control the lamp by clicking on the icons, but the icon will not get the ACTIVE attribute and the icon will not be active either.

**light_profiles.csv:**
_id,x,y,brightness
bright,0,0,254
dimmed,0.457,0.408,150
nightlight,0.457,0.408,38_

**ui-lovelace.yaml:**
_light_profiles:
  bright: '0,0,254'
  background: '0.457,0.408,150'
  dimmed: '0.457,0.408,38'_

**My custom card:**
type: 'custom:light-with-profiles'
title: Nappali
debug: true
entities:
  - entity: light.yeelight_ceiling5_0x0000000007d04907
    name: Mennyezet
    icon: 'mdi:ceiling-light'
    profiles:
      - name: bright
        icon: 'mdi:brightness-5'
      - name: dimmed
        icon: 'mdi:brightness-4'
      - name: nightlight
        icon: 'mdi:brightness-3'
  - entity: light.nappali_e14
    name: Éjjeli lámpa
    icon: 'mdi:lightbulb-outline'
    profiles:
      - name: bright
        icon: 'mdi:brightness-5'
      - name: dimmed
        icon: 'mdi:brightness-4'
      - name: nightlight
        icon: 'mdi:brightness-3'

Do you know a solution? Any ideas?
Thanks: István

**Comment by mdewyer** [comment]
I also had these issues, but have been able to get it working with some adjustments.

First, I had to modify the `light-with-profiles.js` file, and my `profileClass` function is now this:

```
  profileClass(stateObj, profile) {

    let brightness = stateObj.attributes.brightness || stateObj.brightness;

    if (brightness) {

      let xyColor = stateObj.attributes.xy_color || stateObj.xy_color;
      let xyColorString = '0,0';
      if (xyColor) xyColorString = xyColor.toString();

      const activeProfile = `${xyColorString},${brightness.toString()}`;

      if (activeProfile === this.lightProfiles[profile]) {
        return true;
      }

    }

    return false;
  }
```
Second, instead of putting `light_profiles:` in ui-lovelace.yaml, I put it into the view's yaml (Overview -> Edit Dashboard -> Raw configuration editor) at the top level. Not sure if this is necessary or if my ui-lovelace.yaml file is messed up.

Third, the `light_profiles.csv` file doesn't seem to be necessary (nor can I find a reference to it in the code) so I've deleted that file.

With these changes it seems to be working as intended!
