### ISSUE TITLE
only use brightness

### ISSUE THREAD

**Issue by tsolli** [tcarlsen/lovelace-light-with-profiles#4]
Hi!

I have some KNX lights that wont work if I also send in XY color.
looks like they only work when I use entity and  brightness. is it possible to have this as an option? only brightness.

**Comment by tcarlsen** [comment]
this sounds like something that also fix https://community.home-assistant.io/t/lovelace-card-light-with-profiles/121398/24?u=tcarlsen

I just release 2.1.0 with a debug mode. please try to enable that `debug: true` and tell me what values your lights return.

**Comment by tcarlsen** [comment]
@tsolli please go and upgrade to 2.2.0 I hope I made it possible to make brightness only profiles by setting x,y to 0,0 like this:

```yaml
light_profiles:
  brightness_only: '0,0,150'
```

**Comment by tsolli** [comment]
Sorry for the late reply. I didnt see you commented.
@tcarlsen 

looks like if I send in XY_color it doesnt dim.
so If I try with Developer Tools in HA with this :

entity_id: light.kitchen
transition: 60
xy_color:
  - 0
  - 0
brightness: 10

it only turns on the light but cant change the brightness.

but If I use this it works:
entity_id: light.kitchen
transition: 60
brightness: 10

**Comment by tcarlsen** [comment]
sounds like an issue with the native light_profiles in HA.

can you use light_profiles via the dev tool?
